model:
  name: "lgb"
  params:
    n_estimators: 3000
    learning_rate: 0.01
    num_leaves: 63
    subsample: 0.8
    colsample_bytree: 0.8
    reg_alpha: 0.2
    reg_lambda: 0.6
    min_child_samples: 50
    random_state: 42